PATH_TRAINING = datasets/NELL995/NELL995_train.txt

PATH_OUTPUT   = rule_mining/NELL995/split_mined_rules

SNAPSHOTS_AT = 1000

WORKER_THREADS = 32

THRESHOLD_CONFIDENCE = 0.1

THRESHOLD_CORRECT_PREDICTIONS = 2

MAX_LENGTH_ACYCLIC = 0

MAX_LENGTH_GROUNDED_CYCLIC = 0

MAX_LENGTH_CYCLIC = 3
ZERO_RULES_ACTIVE = false
REWRITE_REFLEXIV = false 
SAFE_PREFIX_MODE = true 
x