PATH_TRAINING = datasets/NELL995/NELL995_train.tsv
#PATH_VALID    = datasets/NELL995/NELL995_valid.txt
PATH_TEST     = datasets/NELL995/NELL995_test.tsv
PATH_PREDICTIONS =  rule_mining/NELL995/NELL995_predictions




TOP_K_OUTPUT = 100