PATH_TRAINING = datasets/NELL995/data/NELL995_train.tsv
PATH_VALID    = datasets/NELL995/data/NELL995_valid.tsv
PATH_TEST     = datasets/NELL995/data/NELL995_test.tsv
#PATH_PREDICTIONS =  datasets/NELL995/predictions/NELL995_original_anyburl_predictions
#PATH_PREDICTIONS =  datasets/NELL995/predictions/temp
#PATH_PREDICTIONS =  datasets/NELL995/predictions/temp_nm
PATH_PREDICTIONS =  datasets/NELL995/predictions/temp_no_rep




TOP_K_OUTPUT = 100