PATH_TRAINING = datasets/NELL995/data/NELL995_train.tsv
PATH_VALID    = datasets/NELL995/data/NELL995_valid.tsv
PATH_TEST     = datasets/NELL995/data/NELL995_test.tsv

PATH_OUTPUT = datasets/NELL995/predictions/NELL995_original_anyburl_predictions

PATH_RULES    = datasets/NELL995/rules/NELL995_rules_anyburl-100


WORKER_THREADS = 16

TOP_K_OUTPUT = 100